name: time-quote
version: 1.9.0.0
license: GPL-3
license-file: COPYING
synopsis: Quasi-quoters for dates and times
author: Thomas Tuegel <ttuegel@mailbox.org>
maintainer: Thomas Tuegel <ttuegel@mailbox.org>
copyright: (C) 2018  Thomas Tuegel <ttuegel@mailbox.org>
category: Time

dependencies:
  - base < 5
  - template-haskell
  - time == 1.9.*

ghc-options: -Wall

library:
  source-dirs: src/
  exposed-modules:
    - Data.Time.Quote

tests:
  doctest:
    main: doctest-driver.hs
    source-dirs: test/
    ghc-options: -threaded
    dependencies:
      - base
      - doctest
      - doctest-discover
